<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OData" Version="9.5.0" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.10" />
    <PackageReference Include="System.Text.Encodings.Web" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JustAnAiAgent.MCP\JustAnAiAgent.MCP.csproj" />
    <ProjectReference Include="..\JustAnAiAgent.Services\JustAnAiAgent.Services.csproj" />
    <ProjectReference Include="..\JustAnAiAgent.Objects\JustAnAiAgent.Objects.csproj" />
  </ItemGroup>

</Project>
